[general]
live-config = 1
framerate = 120
autosens = 0
sensitivity = 65
scaling = decibel
bars = 0
bar_width = 3
bar_spacing = 2
center_align = 1
max_height = 55

[input]
method = pipewire
source = auto

[output]
method = noncurses
orientation = horizontal
channels = stereo
split_stereo = 1
synchronized_sync = 0

[color]
theme = "noctalia"

[smoothing]
monstercat = 1
noise_reduction = 85
