[general]
live-config = 1
framerate = 120
autosens = 1
scaling = decibel
bars = 0
bar_width = 1
bar_spacing = 0

[input]
method = pipewire
source = auto

[output]
method = noncurses
orientation = bottom
channels = stereo
synchronized_sync = 0

[color]
theme = "noctalia"

[smoothing]
monstercat = 1
waves = 1
noise_reduction = 55
