[general]
live-config = 1
framerate = 120
autosens = 1
scaling = decibel
bars = 0
bar_width = 1
bar_spacing = 1

[input]
method = pipewire
source = auto

[output]
method = noncurses
orientation = vertical
channels = stereo
split_stereo = 1
synchronized_sync = 0

[color]
theme = "noctalia"

[smoothing]
noise_reduction = 60
