-- Generated by Noctalia. Do not edit.

CACHYLGREEN = "rgba({{ colors.primary.default.hex_stripped }}d9)"
CACHYMGREEN = "rgba({{ colors.secondary.default.hex_stripped }}d9)"
CACHYDGREEN = "rgba({{ colors.tertiary.default.hex_stripped }}d9)"
CACHYLBLUE  = "rgba({{ colors.secondary.default.hex_stripped }}ff)"
CACHYMBLUE  = "rgba({{ colors.primary_container.default.hex_stripped }}ff)"
CACHYDBLUE  = "rgba({{ colors.tertiary.default.hex_stripped }}ff)"
CACHYWHITE  = "rgba({{ colors.on_surface.default.hex_stripped }}ff)"
CACHYGREY   = "rgba({{ colors.on_surface_variant.default.hex_stripped }}ff)"
CACHYGRAY   = "rgba({{ colors.outline_variant.default.hex_stripped }}ff)"
