-- Generated by Noctalia. Do not edit.

return {
  base00 = "{{ colors.terminal_background.default.hex }}",
  base01 = "{{ colors.terminal_normal_black.default.hex }}",
  base02 = "{{ colors.terminal_selection_bg.default.hex }}",
  base03 = "{{ colors.terminal_bright_black.default.hex }}",
  base04 = "{{ colors.terminal_normal_white.default.hex }}",
  base05 = "{{ colors.terminal_foreground.default.hex }}",
  base06 = "{{ colors.terminal_bright_white.default.hex }}",
  base07 = "{{ colors.terminal_bright_white.default.hex }}",
  base08 = "{{ colors.terminal_normal_red.default.hex }}",
  base09 = "{{ colors.terminal_normal_yellow.default.hex }}",
  base0A = "{{ colors.terminal_bright_yellow.default.hex }}",
  base0B = "{{ colors.terminal_normal_green.default.hex }}",
  base0C = "{{ colors.terminal_normal_cyan.default.hex }}",
  base0D = "{{ colors.terminal_normal_blue.default.hex }}",
  base0E = "{{ colors.terminal_normal_magenta.default.hex }}",
  base0F = "{{ colors.terminal_bright_red.default.hex }}",
}
