command = /usr/bin/zsh
theme = noctalia
font-size = 13
background-opacity = 0.98
window-theme = ghostty
resize-overlay = never
gtk-toolbar-style = flat
shell-integration-features = no-cursor,ssh-env

# Avoid Ghostty's Wayland rendering slowdown under Hyprland.
async-backend = epoll
