#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Ghostty tab workaround - force re-layout when tabs are created/destroyed
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

$HOME/.config/yabai/create_spaces.sh

# global settings
yabai -m config \
    external_bar all:35:0 \
    menubar_opacity 1.0 \
    mouse_follows_focus off \
    focus_follows_mouse off \
    display_arrangement_order default \
    window_origin_display default \
    window_placement second_child \
    window_insertion_point focused \
    window_zoom_persist on \
    window_shadow on \
    window_animation_duration 0.0 \
    window_animation_easing ease_out_circ \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.90 \
    window_opacity off \
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.50 \
    split_type auto \
    auto_balance off \
    top_padding 12 \
    bottom_padding 12 \
    left_padding 12 \
    right_padding 12 \
    window_gap 06 \
    layout bsp \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m rule --add app="^Spotify$" space=8
yabai -m rule --add app="^Discord$" space=7

yabai -m config layout bsp

echo "yabai configuration loaded.."
