gui:
  theme:
    activeBorderColor:
      - "#5ddbbd"
      - bold
    inactiveBorderColor:
      - "#86d6bf"
    searchingActiveBorderColor:
      - "#8ad0ee"
      - bold
    optionsTextColor:
      - "#b4cad5"
    selectedLineBgColor:
      - "#b4cad5"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b4cad5"
    cherryPickedCommitBgColor:
      - "#8ad0ee"
    markedBaseCommitFgColor:
      - "#8ad0ee"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#d9e4eb"
  sidePanelWidth: 0.2
git:
  pagers:
    - colorArg: never
      pager: "ydiff -p cat -s --wrap --width={{columnWidth}}"
