gui:
  theme:
    activeBorderColor:
      - "#50dbcf"
      - bold
    inactiveBorderColor:
      - "#81d5cc"
    searchingActiveBorderColor:
      - "#93cdf6"
      - bold
    optionsTextColor:
      - "#b6c9d8"
    selectedLineBgColor:
      - "#b6c9d8"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b6c9d8"
    cherryPickedCommitBgColor:
      - "#93cdf6"
    markedBaseCommitFgColor:
      - "#93cdf6"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#dae4ed"
  sidePanelWidth: 0.2
git:
  pagers:
    - colorArg: never
      pager: "ydiff -p cat -s --wrap --width={{columnWidth}}"
