#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# NVM is now lazy-loaded in .zshrc - see ~/.config/zsh/scripts/nvm-lazy-load.zsh
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/alias/default" ]; then
  nvm_default="$(cat "$NVM_DIR/alias/default")"
  if [ -s "$NVM_DIR/alias/$nvm_default" ]; then
    nvm_default="$(cat "$NVM_DIR/alias/$nvm_default")"
  fi
  case "$nvm_default" in
    v*) ;;
    *) nvm_default="v${nvm_default}" ;;
  esac
  if [ -d "$NVM_DIR/versions/node/$nvm_default/bin" ]; then
    export PATH="$NVM_DIR/versions/node/$nvm_default/bin:$PATH"
  fi
fi

# Load Cargo environment
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# Load Go
export PATH="/usr/local/go/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"

# rbenv shims must be on PATH ahead of system Ruby so non-interactive shells
# and subprocesses resolve the project Ruby before /usr/bin/ruby.
export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
